version: "3.1"

services:
  api:
    build: .
    ports:
      - "3333:3333"
    links:
      - redis
      - mongo
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  mongo:
    image: mongo
    command: --serviceExecutor adaptive
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: nature
      MONGO_INITDB_ROOT_PASSWORD: nature
    volumes: 
      - "/tmp/mongodb:/data/db"